---
version: 0.0.9
slug: multipan_flasher
name: Multipan Flasher
description: Silicon Labs multipan firmware flasher add-on
url: >
  https://github.com/darkxst/test-addon/tree/main/multipan_flasher
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
hassio_api: true
hassio_role: admin
image: darkxst/{arch}-multipan-flasher
init: false
options:
  device: null
  bootloader_baudrate: "115200"
  flow_control: true
  verbose: false
schema:
  device: device(subsystem=tty)?
  bootloader_baudrate: list(57600|115200|230400|460800|921600)
  flow_control: bool?
  hardware: list(elelabs|zbdongle-e|zb-gw04-1v1|zb-gw04-1v2)?
  firmware_url: str?
  verbose: bool?
stage: experimental
startup: application
boot: auto
