---
# yamllint disable rule:line-length
blank_issues_enabled: false
contact_links:
  - name: I have a question or need support
    url: https://www.home-assistant.io/help
    about: We use GitHub for tracking bugs, check this website for resources on getting help.
  - name: Community Forum
    url: https://community.home-assistant.io/
    about: Home Assistant Community Forum is great for all general help
  - name: I'm unsure where to go
    url: https://www.home-assistant.io/join-chat
    about: If you are unsure where to go, then joining chat is recommended; Just ask!
